import type { DataSource, SeriesUnit } from "@/types/macro";

export type SeriesSpec = {
  key: string;
  label: string;
  shortLabel: string;
  source: DataSource;
  unit: SeriesUnit;
  description: string;
  providerId: string;
  lookbackYears: number;
  color: string;
  proxyNote?: string;
};

export const SERIES_CATALOG: SeriesSpec[] = [
  {
    key: "sp500",
    label: "S&P 500",
    shortLabel: "S&P 500",
    source: "yahoo",
    unit: "index",
    description: "US Large Caps (Marktbreite nur bedingt sichtbar).",
    providerId: "^GSPC",
    lookbackYears: 3,
    color: "#2563eb",
  },
  {
    key: "nasdaq100",
    label: "Nasdaq 100",
    shortLabel: "Nasdaq 100",
    source: "yahoo",
    unit: "index",
    description: "Tech-/Growth-lastiger US-Index.",
    providerId: "^NDX",
    lookbackYears: 3,
    color: "#7c3aed",
  },
  {
    key: "sp500_equal_weight",
    label: "S&P 500 Equal Weight (Proxy)",
    shortLabel: "S&P EW (RSP)",
    source: "yahoo",
    unit: "usd",
    description: "Equal-Weight-Prox y via ETF RSP statt Index-Spotserie.",
    providerId: "RSP",
    lookbackYears: 3,
    color: "#0f766e",
    proxyNote: "RSP ETF als praktikabler Proxy für S&P 500 Equal Weight.",
  },
  {
    key: "vix",
    label: "VIX",
    shortLabel: "VIX",
    source: "yahoo",
    unit: "index",
    description: "Implizite Aktienvolatilität (Risk Sentiment).",
    providerId: "^VIX",
    lookbackYears: 3,
    color: "#dc2626",
  },
  {
    key: "oil",
    label: "WTI Öl (Front Month)",
    shortLabel: "WTI Öl",
    source: "yahoo",
    unit: "usd",
    description: "WTI Rohöl-Futures als Inflations-/Konjunkturinput.",
    providerId: "CL=F",
    lookbackYears: 3,
    color: "#b45309",
  },
  {
    key: "fedfunds",
    label: "Fed Funds Rate",
    shortLabel: "Fed Funds",
    source: "fred",
    unit: "percent",
    description: "US-Leitzins (effektiver Fed Funds, FRED Serie FEDFUNDS).",
    providerId: "FEDFUNDS",
    lookbackYears: 10,
    color: "#111827",
  },
  {
    key: "cpi",
    label: "US CPI (CPIAUCSL)",
    shortLabel: "CPI",
    source: "fred",
    unit: "index",
    description: "US Verbraucherpreisindex (Headline CPI, saisonbereinigt).",
    providerId: "CPIAUCSL",
    lookbackYears: 10,
    color: "#ea580c",
  },
  {
    key: "unrate",
    label: "US Unemployment Rate",
    shortLabel: "Arbeitslosenquote",
    source: "fred",
    unit: "percent",
    description: "US-Arbeitslosenquote (UNRATE, monatlich).",
    providerId: "UNRATE",
    lookbackYears: 10,
    color: "#7f1d1d",
  },
  {
    key: "dgs10",
    label: "US 10Y Treasury Yield",
    shortLabel: "UST 10Y",
    source: "fred",
    unit: "percent",
    description: "10-jährige US-Treasury-Rendite (DGS10).",
    providerId: "DGS10",
    lookbackYears: 10,
    color: "#1d4ed8",
  },
  {
    key: "dgs2",
    label: "US 2Y Treasury Yield",
    shortLabel: "UST 2Y",
    source: "fred",
    unit: "percent",
    description: "2-jährige US-Treasury-Rendite (DGS2).",
    providerId: "DGS2",
    lookbackYears: 10,
    color: "#9333ea",
  },
  {
    key: "ig_oas",
    label: "US Investment Grade OAS",
    shortLabel: "IG OAS",
    source: "fred",
    unit: "percent",
    description: "ICE BofA US Corporate Index OAS (Spread in Prozentpunkten, FRED).",
    providerId: "BAMLC0A0CM",
    lookbackYears: 10,
    color: "#0369a1",
  },
  {
    key: "hy_oas",
    label: "US High Yield OAS",
    shortLabel: "HY OAS",
    source: "fred",
    unit: "percent",
    description: "ICE BofA US High Yield Index OAS (Spread in Prozentpunkten, FRED).",
    providerId: "BAMLH0A0HYM2",
    lookbackYears: 10,
    color: "#be123c",
  },
  {
    key: "payrolls",
    label: "Nonfarm Payrolls",
    shortLabel: "Payrolls",
    source: "fred",
    unit: "thousand_persons",
    description: "Beschäftigte (PAYEMS, in Tausend Personen).",
    providerId: "PAYEMS",
    lookbackYears: 10,
    color: "#059669",
  },
];
